export const USERS_ACTIONS_TYPES = {
    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILED: 'fETCH_USERS_FAILED',
    SET_USERS: 'SET_USERS',
    SET_USERS_PAGE_NUMBER: 'SET_USERS_PAGE_NUMBER',
    SET_USERS_OFFSET: 'SET_USERS_OFFSET',
    SET_USERS_CLICKED_ROW: 'SET_USERS_CLICKED_ROW',
    SET_USERS_RAW_DATA: 'SET_USERS_RAW_DATA',
    SET_USERS_SEARCH_FILTERS: 'SET_SEARCH_FILTERS',
    SET_USERS_IS_LOADING: 'SET_IS_LOADING'
}