export const LEADS_ACTIONS_TYPES = {
    FETCH_LEADS_START: 'FETCH_LEADS_START',
    FETCH_LEADS_SUCCESS: 'FETCH_LEADS_SUCCESS',
    FETCH_LEADS_FAILED: 'fETCH_LEADS_FAILED',
    SET_LEADS: 'SET_LEADS',
    SET_LEADS_PAGE_NUMBER: 'SET_LEADS_PAGE_NUMBER',
    SET_LEADS_OFFSET: 'SET_LEADS_OFFSET',
    SET_CLICKED_ROW: 'SET_CLICKED_ROW',
    SET_SHOW_EDIT_MODAL: 'SET_SHOW_EDIT_MODAL',
    SET_SHOW_CONFIRM_UPDATE_MODAL: 'SET_SHOW_CONFIRM_UPDATE_MODAL',
    SET_LEADS_RAW_DATA: 'SET_LEADS_RAW_DATA',
    SET_LEADS_UPDATE_ERROR: 'SET_LEADS_UPDATE_ERROR',
    SET_LEADS_DELETE_ERROR: 'SET_LEADS_DELETE_ERROR',
    SET_LEADS_SUCCESSFULLY_DELETED: 'SET_LEADS_SUCCESSFULLY_DELETED',
    SET_LEADS_SUCCESSFULLY_UPDATED: 'SET_LEADS_SUCCESSFULLY_UPDATED',
    SET_SEARCH_FILTERS: 'SET_SEARCH_FILTERS'
}