export const LEADS_ACTIONS_TYPES = {
    FETCH_LEADS_START: 'FETCH_LEADS_START',
    FETCH_LEADS_SUCCESS: 'FETCH_LEADS_SUCCESS',
    FETCH_LEADS_FAILED: 'fETCH_LEADS_FAILED',
    SET_LEADS: 'SET_LEADS'
}