export const DASHBOARD_ACTIONS_TYPES = {
    SET_IS_SIDE_NAV_BAR_OPEN: 'SET_IS_SIDE_NAV_BAR_OPEN',
    SET_IS_PROFILE_DROP_DOWN_OPEN: 'SET_IS_PROFILE_DROP_DOWN_OPEN',
    SET_IS_DASHBOARD_STATS_LOADING: 'SET_IS_DASHBOARD_STATS_LOADING',
    FETCH_DASHBOARD_STATS_START: 'FETCH_DASHBOARD_STATS_START',
    FETCH_DASHBOARD_STATS_SUCCESS: 'FETCH_DASHBOARD_STATS_SUCCESS',
    FETCH_DASHBOARD_STATS_FAILED: 'fETCH_DASHBOARD_STATS_FAILED',
}